[0] pass: main: 12: argc == 2
[1] pass: main: 13: ud_init(&doc) == 1
[2] pass: main: 14: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing 11.t depth 0
debug: ud_tree_build: paren open
debug: ud_tree_build: processing 11.t depth 1
debug: ud_tree_build: symbol: include
debug: ud_tree_build: processing includefail depth 0
debug: ud_tree_build: paren open
debug: ud_tree_build: processing includefail depth 1
debug: ud_tree_build: symbol: include
debug: ud_tree_build: fail depth 1: file does not exist
debug: ud_tree_build: fail depth 0: file does not exist
debug: ud_tree_build: fail depth 1: file does not exist
debug: ud_tree_build: fail depth 0: file does not exist
[3] pass: main: 15: ud_parse(&doc) == 0
[4] pass: main: 16: ud_free(&doc) == 1
