[0] pass: main: 26: argc == 2
[1] pass: main: 27: ud_init(&doc) == 1
[2] pass: main: 28: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing 11.t depth 0
debug: ud_tree_build: paren open
debug: ud_tree_build: processing 11.t depth 1
debug: ud_tree_build: symbol: include
debug: ud_tree_build: processing includefail depth 0
debug: ud_tree_build: paren open
debug: ud_tree_build: processing includefail depth 1
debug: ud_tree_build: symbol: include
debug: ud_tree_build: fail depth 1: file does not exist
debug: ud_tree_build: fail depth 0: file does not exist
debug: ud_tree_build: fail depth 1: file does not exist
debug: ud_tree_build: fail depth 0: file does not exist
[3] pass: main: 29: ud_parse(&doc) == 0
error: 11.t: ud_tree_symbol: ud_tree_include failed
error: includefail: ud_tree_symbol: ud_tree_include failed
error: nonexistent: ud_open: nonexistent: file does not exist
[4] pass: main: 33: ud_free(&doc) == 1
