[0] pass: main: 12: argc == 2
[1] pass: main: 13: ud_init(&doc) == 1
[2] pass: main: 14: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing 12.t depth 0
debug: ud_tree_build: string: example
debug: ud_tree_string: inserting implicit para
debug: ud_tree_build: symbol: include
debug: ud_tree_build: fail depth 0: parse error
[3] pass: main: 15: ud_parse(&doc) == 0
[4] pass: main: 16: ud_free(&doc) == 1
