[0] pass: main: 26: argc == 2
[1] pass: main: 27: ud_init(&doc) == 1
[2] pass: main: 28: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing include_stray.t depth 0
debug: ud_tree_build: string: example
debug: ud_tree_string: inserting implicit para
debug: ud_tree_build: symbol: include
debug: ud_tree_build: fail depth 0: parse error
[3] pass: main: 29: ud_parse(&doc) == 0
error: include_stray.t: ud_tree_symbol: ud_tree_include failed
error: include_stray.t: syntax: 0: the include symbol can only appear at the start of a list
[4] pass: main: 33: ud_free(&doc) == 1
