[0] pass: main: 26: argc == 2
[1] pass: main: 27: ud_init(&doc) == 1
[2] pass: main: 28: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing paren4.t depth 0
debug: ud_tree_build: paren open
debug: ud_tree_build: processing paren4.t depth 1
debug: ud_tree_build: paren close
debug: ud_tree_build: empty depth 1
debug: ud_tree_build: paren close
debug: ud_tree_build: fail depth 0: parse error
[3] pass: main: 29: ud_parse(&doc) == 0
error: paren4.t: syntax: 0: unbalanced parenthesis
[4] pass: main: 33: ud_free(&doc) == 1
