[0] pass: main: 12: argc == 2
[1] pass: main: 13: ud_init(&doc) == 1
[2] pass: main: 14: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing footnote_4.t depth 0
debug: ud_tree_build: symbol: footnote
debug: ud_tree_build: string: test
debug: ud_tree_build: string: extra
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
[3] pass: main: 15: ud_parse(&doc) == 1
debug: ud_walk: processing footnote_4.t depth 0
debug: ud_walk: symbol: footnote
error: 0: footnote: too many args
debug: ud_walk: fail depth 0
[4] pass: main: 16: ud_validate(&doc) == 0
[5] pass: main: 17: ud_free(&doc) == 1
