[0] pass: main: 26: argc == 2
[1] pass: main: 27: ud_init(&doc) == 1
[2] pass: main: 28: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing link_ext_3.t depth 0
debug: ud_tree_build: symbol: link-ext
debug: ud_tree_build: symbol: link-ext
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
[3] pass: main: 29: ud_parse(&doc) == 1
debug: ud_walk: processing link_ext_3.t depth 0
debug: ud_walk: symbol: link-ext
debug: ud_walk: fail depth 0
[4] pass: main: 30: ud_validate(&doc) == 0
error: link_ext_3.t: validation_error: 0: link-ext: invalid type for argument 1
[5] pass: main: 34: ud_free(&doc) == 1
