[0] pass: main: 12: argc == 2
[1] pass: main: 13: ud_init(&doc) == 1
[2] pass: main: 14: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing render_header_3.t depth 0
debug: ud_tree_build: symbol: render-header
debug: ud_tree_build: paren open
debug: ud_tree_build: processing render_header_3.t depth 1
debug: ud_tree_build: symbol: item
debug: ud_tree_build: string: test
debug: ud_tree_build: paren close
debug: ud_tree_build: success depth 1
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
[3] pass: main: 15: ud_parse(&doc) == 1
debug: ud_walk: processing render_header_3.t depth 0
debug: ud_walk: symbol: render-header
error: 0: render-header: invalid type for argument 1
debug: ud_walk: fail depth 0
[4] pass: main: 16: ud_validate(&doc) == 0
[5] pass: main: 17: ud_free(&doc) == 1
