[0] pass: main: 30: argc == 4
[1] pass: main: 41: r != 0
[2] pass: main: 43: ud_init(&doc) == 1
[3] pass: main: 47: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing 1.t depth 0
debug: ud_tree_build: string: hello
debug: ud_tree_string: inserting implicit para
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
[4] pass: main: 48: ud_parse(&doc) == 1
debug: ud_walk: processing 1.t depth 0
debug: ud_walk: symbol: para
debug: ud_walk: string: "hello"
debug: ud_walk: list: end
debug: ud_walk: success depth 0
[5] pass: main: 49: ud_validate(&doc) == 1
debug: cb_part_init: adding root part
debug: part_add: part 0
debug: part_add: part split 0
debug: ud_walk: processing 1.t depth 0
debug: ud_walk: symbol: para
debug: ud_walk: string: "hello"
debug: ud_walk: list: end
debug: ud_walk: success depth 0
debug: cb_part_finish: 1 parts, 1 files
[6] pass: main: 50: ud_partition(&doc) == 1
debug: ud_render_doc: rendering
notice: create 0.html
debug: ud_render_node: rendering
debug: r_init: file init
debug: ud_walk: processing 1.t depth 0
debug: ud_walk: symbol: para
debug: ud_walk: string: "hello"
debug: ud_walk: list: end
debug: ud_walk: success depth 0
debug: r_finish: file finish
debug: ud_render_node: rendering done
[7] pass: main: 51: ud_render_doc(&doc, &r_opts, r, ".") == 1
[8] pass: main: 52: ud_free(&doc) == 1
