[0] pass: main: 30: argc == 4
[1] pass: main: 41: r != 0
[2] pass: main: 43: ud_init(&doc) == 1
[3] pass: main: 47: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing 5.t depth 0
debug: ud_tree_build: paren open
debug: ud_tree_build: processing 5.t depth 1
debug: ud_tree_build: symbol: section
debug: ud_tree_build: paren open
debug: ud_tree_build: processing 5.t depth 2
debug: ud_tree_build: symbol: para
debug: ud_tree_build: string: hello
debug: ud_tree_build: paren close
debug: ud_tree_build: success depth 2
debug: ud_tree_build: paren close
debug: ud_tree_build: success depth 1
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
[4] pass: main: 48: ud_parse(&doc) == 1
debug: ud_walk: processing 5.t depth 0
debug: ud_walk: list
debug: ud_walk: processing 5.t depth 1
debug: ud_walk: symbol: section
debug: ud_walk: list
debug: ud_walk: processing 5.t depth 2
debug: ud_walk: symbol: para
debug: ud_walk: string: "hello"
debug: ud_walk: list: end
debug: ud_walk: success depth 2
debug: ud_walk: list: end
debug: ud_walk: success depth 1
debug: ud_walk: list: end
debug: ud_walk: success depth 0
[5] pass: main: 49: ud_validate(&doc) == 1
debug: cb_part_init: adding root part
debug: part_add: part 0
debug: part_add: part split 0
debug: ud_walk: processing 5.t depth 0
debug: ud_walk: list
debug: ud_walk: processing 5.t depth 1
debug: ud_walk: symbol: section
debug: part_section: part stack size 1
debug: part_section: split threshold exceeded - not splitting
debug: part_add: part 1
debug: ud_walk: list
debug: ud_walk: processing 5.t depth 2
debug: ud_walk: symbol: para
debug: ud_walk: string: "hello"
debug: ud_walk: list: end
debug: ud_walk: success depth 2
debug: ud_walk: list: end
debug: cb_part_list_end: part stack size 1
debug: ud_walk: success depth 1
debug: ud_walk: list: end
debug: ud_walk: success depth 0
debug: cb_part_finish: 2 parts, 1 files
[6] pass: main: 50: ud_partition(&doc) == 1
debug: ud_render_doc: rendering
notice: create 0.html
debug: ud_render_node: rendering
debug: r_init: file init
debug: ud_walk: processing 5.t depth 0
debug: ud_walk: list
debug: ud_walk: processing 5.t depth 1
debug: ud_walk: symbol: section
debug: r_symbol: pushed part
debug: x_tag_section: section open
debug: ud_walk: list
debug: ud_walk: processing 5.t depth 2
debug: ud_walk: symbol: para
debug: ud_walk: string: "hello"
debug: ud_walk: list: end
debug: ud_walk: success depth 2
debug: ud_walk: list: end
debug: r_list_end: popped part
debug: x_tag_end_section: section close
debug: ud_walk: success depth 1
debug: ud_walk: list: end
debug: ud_walk: success depth 0
debug: r_finish: file finish
debug: ud_render_node: rendering done
[7] pass: main: 51: ud_render_doc(&doc, &r_opts, r, ".") == 1
[8] pass: main: 52: ud_free(&doc) == 1
