#!/bin/sh

fatal()
{
  echo "fatal: $1"
  exit 1
}

if [ $# -ne 1 ]; then fatal "not enough arguments (file)"; fi
if [ ! -x passrender ]; then fatal "passrender not found or not executable"; fi

file="$1"
prog_exp="$file.nroff.exp"
prog_out="$file.nroff.out"
render_exp="$file.nroff.r_exp"
render_out="0.nrf"

rm -f "$prog_out" "$render_out"

./passrender "$file.t" nroff 0 >"$prog_out" 2>&1
if [ $? -ne 0 ]; then fatal "test failed"; fi

cmp "$prog_out" "$prog_exp" || fatal "program output comparison failed"
cmp "$render_out" "$render_exp" || fatal "render output comparison failed"
