#!/bin/sh

remove()
{
  echo "remove $1"
  rm -f $1
}

dir_list=""
for dir in `ls`
do
  if [ -d "$dir" ]
  then
    files="`find "$dir" -name '*.out'`"
    files="$files `find "$dir" -name '*.txt'`"
    files="$files `find "$dir" -name '*.html'`"
    files="$files `find "$dir" -name '*.nrf'`"
    files="$files `find "$dir" -name '*.tex'`"

    for file in $files
    do
      remove $file
    done
  fi
done
