#!/bin/sh

lib_failed=0
lib_passed=0
lib_failed_bad=0
lib_tests=0

inspect_ret()
{
  ret=$1
  test=$2
  case $ret in
    0)
      echo passed $test
      lib_passed=`expr $lib_passed + 1` >/dev/null 2>&1
      ;;
    1)
      echo failed $test
      lib_failed=`expr $lib_failed + 1` >/dev/null 2>&1
      ;;
    *)
      echo crash  $test
      lib_failed_bad=`expr $lib_failed_bad + 1` >/dev/null 2>&1
      ;;
  esac
}

dir_tests()
{
  cur_dir="$1"

  tests=`ls *.t 2>/dev/null`
  if [ $? -eq 0 ]
  then
    for t in $tests
    do
      tag=`echo $t | awk -F. '{print $1}'`
      tag=`basename "$tag"`

      runners=`ls *.run`
      if [ $? -eq 0 ]
      then
        for runner in $runners
        do
          lib_tests=`expr $lib_tests + 1` >/dev/null 2>&1
          ./"$runner" "$tag"
          inspect_ret $? "$dir/$tag"
        done
      fi
    done
  fi
}

list_dirs()
{
  dir_list=""
  for dir in `ls 2>/dev/null`
  do
    if [ -d "$dir" ]; then dir_list="$dir_list $dir"; fi
  done
  echo $dir_list
}

#
# entry
#

base_dir=`pwd`

echo '-- tests start --'
for dir in `list_dirs`
do
  cd "$dir"
  dir_tests "$dir"
  cd "$base_dir"
done

cat <<EOF
-- tests end --
tests      $lib_tests
passed     $lib_passed
failed     $lib_failed
crashed    $lib_failed_bad
EOF
