[0] pass: main: 12: argc == 2
[1] pass: main: 13: ud_error_init(&ud_errors) == 1
[2] pass: main: 14: ud_init(&doc) == 1
[3] pass: main: 15: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing 10.t depth 0
debug: ud_tree_build: symbol: include
debug: ud_tree_build: processing example depth 0
debug: ud_tree_build: paren open
debug: ud_tree_build: processing example depth 1
debug: ud_tree_build: symbol: para
debug: ud_tree_build: string: example para1
debug: ud_tree_build: paren close
debug: ud_tree_build: success depth 1
debug: ud_tree_build: paren open
debug: ud_tree_build: processing example depth 1
debug: ud_tree_build: symbol: para
debug: ud_tree_build: string: example para2
debug: ud_tree_build: paren close
debug: ud_tree_build: success depth 1
debug: ud_tree_build: paren open
debug: ud_tree_build: processing example depth 1
debug: ud_tree_build: symbol: para
debug: ud_tree_build: string: example para3
debug: ud_tree_build: paren close
debug: ud_tree_build: success depth 1
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
[4] pass: main: 16: ud_parse(&doc) == 1
[5] pass: main: 17: ud_free(&doc) == 1
