[0] pass: main: 12: argc == 2
[1] pass: main: 13: ud_init(&doc) == 1
[2] pass: main: 14: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing 12.t depth 0
debug: ud_tree_build: paren open
debug: ud_tree_build: processing 12.t depth 1
debug: ud_tree_build: paren open
debug: ud_tree_build: processing 12.t depth 2
debug: ud_tree_build: paren open
debug: ud_tree_build: processing 12.t depth 3
debug: ud_tree_build: paren open
debug: ud_tree_build: processing 12.t depth 4
debug: ud_tree_build: symbol: para
debug: ud_tree_build: string: reduced
debug: ud_tree_build: paren close
debug: ud_tree_build: success depth 4
debug: ud_tree_build: paren close
debug: ud_tree_reduce: reduced list
debug: ud_tree_build: success depth 3
debug: ud_tree_build: paren close
debug: ud_tree_reduce: reduced list
debug: ud_tree_build: success depth 2
debug: ud_tree_build: paren close
debug: ud_tree_reduce: reduced list
debug: ud_tree_build: success depth 1
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
[3] pass: main: 15: ud_parse(&doc) == 1
[4] pass: main: 16: ud_free(&doc) == 1
