[0] pass: main: 12: argc == 2
[1] pass: main: 13: ud_init(&doc) == 1
[2] pass: main: 14: ud_open(&doc, argv[1]) == 1
debug: ud_tree_build: processing encoding_1.t depth 0
debug: ud_tree_build: symbol: encoding
debug: ud_tree_build: string: utf-8
debug: ud_tree_build: eof
debug: ud_tree_build: success depth 0
[3] pass: main: 15: ud_parse(&doc) == 1
debug: ud_walk: processing encoding_1.t depth 0
debug: ud_walk: symbol: encoding
debug: ud_walk: string: "utf-8"
debug: ud_walk: list: end
debug: ud_walk: success depth 0
[4] pass: main: 16: ud_validate(&doc) == 1
[5] pass: main: 17: ud_free(&doc) == 1
